version: '3.8'

services:
  # Redis Master
  redis-master:
    image: redis:7-alpine
    container_name: redis-master
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --replica-read-only no
    volumes:
      - redis-master-data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Redis Replica
  redis-replica:
    image: redis:7-alpine
    container_name: redis-replica
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes --replicaof redis-master 6379
    depends_on:
      redis-master:
        condition: service_healthy
    volumes:
      - redis-replica-data:/data
    networks:
      - redis-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 3

  # Redis Sentinel 1
  redis-sentinel-1:
    image: redis:7-alpine
    container_name: redis-sentinel-1
    ports:
      - "26379:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel1.conf:/etc/redis/sentinel.conf
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica:
        condition: service_healthy
    networks:
      - redis-network

  # Redis Sentinel 2
  redis-sentinel-2:
    image: redis:7-alpine
    container_name: redis-sentinel-2
    ports:
      - "26380:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel2.conf:/etc/redis/sentinel.conf
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica:
        condition: service_healthy
    networks:
      - redis-network

  # Redis Sentinel 3
  redis-sentinel-3:
    image: redis:7-alpine
    container_name: redis-sentinel-3
    ports:
      - "26381:26379"
    command: redis-sentinel /etc/redis/sentinel.conf
    volumes:
      - ./sentinel3.conf:/etc/redis/sentinel.conf
    depends_on:
      redis-master:
        condition: service_healthy
      redis-replica:
        condition: service_healthy
    networks:
      - redis-network

volumes:
  redis-master-data:
  redis-replica-data:

networks:
  redis-network:
    driver: bridge