server:
  port: 9090
spring:
  application:
    name: redisPoc

  datasource:
    url: jdbc:mysql://localhost:3306/redisPoc
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  cache:
    type: redis
    redis:
      key-prefix: "redisPoc:"
      use-key-prefix: true

  data:
    redis:
      host: localhost
      port: 6379
      ttl: 60s
